# Generated by Django 4.1.13 on 2025-08-26 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('role', models.TextField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('artefact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
                ('collection_date', models.DateField()),
                ('details', models.TextField()),
                ('origin_universe_id', models.TextField()),
                ('artefact_type', models.TextField()),
                ('rare_artifact', models.TextField()),
                ('common_artifact', models.TextField()),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universe.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('starting_bidding_price', models.IntegerField()),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universe.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('marketplace_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universe.admin')),
            ],
        ),
        migrations.CreateModel(
            name='PortalTimeScheduler',
            fields=[
                ('travel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.TextField()),
                ('destination', models.TextField()),
                ('date', models.DateField()),
                ('max_capacity', models.IntegerField()),
                ('status', models.TextField()),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universe.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('universe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('universe_type', models.TextField()),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('destroyed_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField()),
                ('visited_intergalectic_beings', models.TextField()),
                ('danger_level', models.IntegerField()),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universe.admin')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.CharField(max_length=30)),
                ('reg_date', models.DateField()),
                ('address', models.CharField(max_length=30)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universe.admin')),
                ('au', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universe.auction')),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universe.marketplace')),
                ('tr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universe.portaltimescheduler')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universe.universe')),
            ],
        ),
        migrations.CreateModel(
            name='RandomEvent',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('effect', models.CharField(max_length=50)),
                ('date_triggered', models.DateField()),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universe.artefact')),
            ],
        ),
        migrations.CreateModel(
            name='JourneyLog',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False)),
                ('destination', models.TextField()),
                ('date', models.DateField()),
                ('status', models.TextField()),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universe.admin')),
            ],
        ),
        migrations.AddField(
            model_name='artefact',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universe.universe'),
        ),
    ]
