# Generated by Django 4.1.13 on 2025-09-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
    ]
