# Generated by Django 4.1.13 on 2025-08-28 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universe', '0002_artefact_auction_artefact_marketplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefact',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='artefact',
            name='marketplace',
        ),
        migrations.RemoveField(
            model_name='universe',
            name='a',
        ),
        migrations.RemoveField(
            model_name='universe',
            name='visited_intergalectic_beings',
        ),
        migrations.AddField(
            model_name='universe',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='universe',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='visited_intergalactic_beings',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='universe',
            name='danger_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='universe',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='universe',
            name='status',
            field=models.CharField(choices=[('Safe', 'Safe'), ('Destroyed', 'Destroyed'), ('Unstable', 'Unstable'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='universe',
            name='universe_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='universe',
            name='universe_type',
            field=models.CharField(choices=[('Prime', 'Prime'), ('Cronenberg', 'Cronenberg'), ('Fantasy', 'Fantasy'), ('Post-Apocalyptic', 'Post-Apocalyptic'), ('Virtual', 'Virtual'), ('Unknown', 'Unknown')], default='Unknown', max_length=50),
        ),
    ]
