# Generated by Django 4.1.13 on 2025-08-28 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universe', '0003_remove_artefact_auction_remove_artefact_marketplace_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universe',
            options={'ordering': ['universe_id']},
        ),
        migrations.AlterField(
            model_name='universe',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='universe',
            name='danger_level',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'High')], default=0),
        ),
    ]
