# Generated by Django 4.1.13 on 2025-08-30 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universe', '0005_alter_admin_admin_id_alter_artefact_artefact_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('canceled', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='username',
        ),
        migrations.RemoveField(
            model_name='journeylog',
            name='a',
        ),
        migrations.RemoveField(
            model_name='portaltimescheduler',
            name='a',
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journeylog',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universe.portaltimescheduler'),
        ),
        migrations.AddField(
            model_name='journeylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portaltimescheduler',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='universe.admin'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='journeylog',
            name='status',
            field=models.TextField(default='Success'),
        ),
        migrations.AlterField(
            model_name='portaltimescheduler',
            name='status',
            field=models.TextField(default='Open'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='booking',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universe.portaltimescheduler'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
