# Generated by Django 4.1.13 on 2025-08-30 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universe', '0006_booking_remove_admin_password_remove_admin_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='journeylog',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='journeylog',
            name='status',
            field=models.CharField(default='Success', max_length=20),
        ),
        migrations.AlterField(
            model_name='journeylog',
            name='travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universe.portaltimescheduler'),
        ),
        migrations.AlterField(
            model_name='portaltimescheduler',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portaltimescheduler',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portaltimescheduler',
            name='max_capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='portaltimescheduler',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portaltimescheduler',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
