# Generated by Django 4.1.13 on 2025-08-30 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0007_remove_booking_booking_date_booking_booked_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaltimescheduler',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='portaltimescheduler',
            name='source',
        ),
        migrations.AddField(
            model_name='portaltimescheduler',
            name='destination_universe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_travel', to='universe.universe'),
        ),
        migrations.AddField(
            model_name='portaltimescheduler',
            name='source_universe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_travel', to='universe.universe'),
        ),
    ]
