# Generated by Django 4.1.13 on 2025-08-31 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0009_remove_booking_travel_booking_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaltimescheduler',
            name='status',
        ),
    ]
